### ISSUE TITLE
Bug Report: PARSE_ERROR_DISC_HEADER

### ISSUE THREAD

**Issue by JC21b** [wiiu-env/wudd#13] opened 2022-08-01 21:40 UTC
When attempting to dump partition as .app, I always get the error ERROR_PARSE_DISC_HEADER
Dumping as WUX and WUD appear to function properly. I'm running Tiramisu and WUDD 1.1.0
Furthermore, (this may be a seperate bug) removing the disc and reinserting it causes the system to no longer read discs. This persists into the Wii U Menu with it regarding discs as invalid. This is fixed with a full shutdown and reboot.

**Comment by Maschell** [comment] 2022-08-01 23:08
- Does it happen to all discs?
- Does it happen with 1.0.0 as well?

**Comment by JC21b** [comment] 2022-08-02 04:00
I was able to dump Splatoon and Kirby RC, but upon removing and reinserting the disc the system again failed to read discs.
Mario Kart 8 and Smash result in the error.
Upon further testing, it appears that it still recognizes Wii discs, and that going to and leaving the Wii Menu also fixes the disc recognition issue.
On 1.0.0 the games that don't work give the error ERROR_PARSE_DISCHEADER and the disc recognition issue is still present.
Those games that worked on 1.1.0 still work on 1.0.0

**Comment by Maschell** [comment] 2022-08-02 08:56
Can you try [this](https://github.com/wiiu-env/wudd/suites/7624702540/artifacts/316752643) .rpx. At least this should avoid the "Invalid Disc" thing.

The `ERROR_PARSE_DISCHEADER` is maybe caused by a dirty/damaged disc? Does it work properly when you try to play it?

**Comment by JC21b** [comment] 2022-08-02 13:36
Can confirm that the invalid disc issue is fixed.
The discs that don't work are clean and free of scratches. In fact, they are in a better condition than the two that did work. They play perfectly.

**Comment by Maschell** [comment] 2022-08-02 13:40
This a very weird. Do you have a computer in the same network as your wii u? Then I give you a debug build via logs via UDP, so we can see whats actually wrong.

**Comment by JC21b** [comment] 2022-08-03 13:54
I do, but unfortunately I think that's outside my ability.

**Comment by DullPilot** [comment] 2022-08-05 04:27
Hey, I'm having the same issue, with the same game (Mario Kart 8). I can cooperate with you to help resolve this issue.

**Comment by Maschell** [comment] 2022-08-05 09:42
Can you use [this](https://github.com/wiiu-env/wudd/files/9267475/wudd-logging.zip) version of WUDD? It won't fix anything, but it'll create a log on the SD Card when dumping the .app files. Additionally it dump the sectors it's reading from the disc.
- Please **only** start the .app dumping, and only start it **once**. Close WUDD, and then copy the `WUDD-` files from the sd card to your computer.
- Please **only** upload the **.log** file. Not the other files, because they cotain copyrighted material.

Hopefully the logs will us to resolve the issue

**Comment by DullPilot** [comment] 2022-08-05 15:10
[WUDD-log-2022-08-05-11-08-34.log](https://github.com/wiiu-env/wudd/files/9269803/WUDD-log-2022-08-05-11-08-34.log)

**Comment by Maschell** [comment] 2022-08-05 15:14
Thanks! Looks like this revivision of MK8 has a additional partition in a slightly different format (probably cotains a game updates on disc). I'll try to add support for it, but in "worst case" I'll ignore it for the dumper, so you can dump the other partitions

**Comment by DullPilot** [comment] 2022-08-05 15:21
Yeah, that would make sense, because when I went to launch the game for the first time, it installed updates from disc, not from the internet. My copy of Super Mario Maker is coming in today, I'll try to dump it with the regular version and see if it works.

**Comment by Maschell** [comment] 2022-08-05 16:53
Can you check if dumping works with the [latest nightly](https://github.com/wiiu-env/wudd/releases/tag/wudd-20220805-165051)?

**Comment by DullPilot** [comment] 2022-08-06 04:31
Trying to dump the game with WUP GX2 Crashed my system, I have [attached ](https://youtu.be/EpoPHfVojs4) a video depicting the problem.

**Comment by DullPilot** [comment] 2022-08-06 16:30
Okay, last night I didn't have the time to retry dumping the disc, but this time it worked. Thanks!

**Comment by Maschell** [comment] 2022-08-06 20:16
Fixed with WUDD 1.2.0

**Closed by Maschell** 2022-08-06 20:16 UTC
